language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=false
  # Our build takes too long for one job, so split targets across multiple jobs
  # triplets come from using BinaryBuilder; triplet.(supported_platforms())
  matrix:
    - TARGET=i686-linux-gnu
    - TARGET=x86_64-linux-gnu
    - TARGET=aarch64-linux-gnu
    - TARGET=arm-linux-gnueabihf
    - TARGET=powerpc64le-linux-gnu
    - TARGET=i686-linux-musl
    - TARGET=x86_64-linux-musl
    - TARGET=aarch64-linux-musl
    - TARGET=arm-linux-musleabihf
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-unknown-freebsd11.1
    - TARGET=i686-w64-mingw32
    - TARGET=x86_64-w64-mingw32
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl $TARGET
deploy:
  provider: releases
  api_key:
    secure: mXbMCPNx9AHSXeLtlx9SruaU2VfDd+bjhb80RWm1IaMbiPRABwZXGAAPM3aFsxLBsEwXDvJvT40mOLfbWz1t72sfFMUIkSwFEU1ycO7KOoqUkDgzwrIXezENDnuC97BhiUA03r45m3/SeW4ukEsg40n+8Syp1x32JGBmpZYrbKctAYAkHOgq8kROhjuG21tQULcXL8l6h6u4wOOpp7S0agEUj8tQ1nr6aGPs1kM8wY0PeqpGZtyykeG73XThAtibedqFWjY4ruBdr0yXntxSDedrNntw6SSL0qLnhwkhLXDTCqR/3jMOLt1T1BlEm4Cr0PoFi9VUKr2DeX/2Kjrdx5Mihg2yqgyLBQ5GAz1Zh6XYVXqEw31b9lQQe690JzVOir01PDZTaawWTeA224WcompnWbtWqCjtwHaqEaqLoJuXM7ck/L7qqZR4Pnip0l5/xyidqHQq+vle2Ci5bhZNdPzVOeFHWXUg2W83xecVSqmWWMqDxtVHGz3h7LKXS8xYkjxwivqNLzC/zEKS9Yxg3aT1ZGwD2aKvrNTxvNdLQn2jXb+EbsitQdkfbQiMAm2w1JleFYiHclhZnV3+5FFB811APDVIKNrujp/SskWCkmKlV4BttQz/+Wyu9OGVtAtRjs9sXPiu9v1O1buN1EpHHvn+CXwvI7xQhLVfnhhljio=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: twadleigh/BoostBuilder
    tags: true
